"""baseline

Revision ID: 936b96e574aa
Revises: 
Create Date: 2026-09-01 14:18:46.929093
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '936b96e574aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级操作。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_bases', 'department_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属部门 id',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级操作。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_bases', 'department_id',
               existing_type=mysql.INTEGER(),
               comment='所属部门 id',
               existing_nullable=False)
    # ### end Alembic commands ###
